// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GVisHuff {
    
    
    public partial class HSEAboutDialog {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Image image1;
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Label label5;
        
        private Gtk.Label label1;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.VBox vbox4;
        
        private Gtk.Label label2;
        
        private Gtk.Label label7;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Label label6;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GVisHuff.HSEAboutDialog
            this.Name = "GVisHuff.HSEAboutDialog";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            // Internal child GVisHuff.HSEAboutDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.image1 = new Gtk.Image();
            this.image1.Name = "image1";
            this.image1.Pixbuf = Gdk.Pixbuf.LoadFromResource("GVisHuff.hse_logo.jpg");
            this.vbox2.Add(this.image1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.image1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("<b>What's this about?</b>");
            this.label5.UseMarkup = true;
            this.vbox3.Add(this.label5);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox3[this.label5]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<b>GVisHuff</b> is a GTK#-based visualizer for the dynamic Huffman encoding algorithm. It simulates the data transfer between two hosts and shows the graphical representation of the compression tree for both the sender and the receiver");
            this.label1.UseMarkup = true;
            this.label1.Wrap = true;
            this.label1.Selectable = true;
            this.vbox3.Add(this.label1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.label1]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            this.vbox3.Add(this.hseparator1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox3[this.hseparator1]));
            w5.Position = 2;
            w5.Expand = false;
            w5.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("<b>GVisHuff</b> was developed as a coursework project by Alexander Tarasikov under the mentorship of professor Sergey Avdoshin");
            this.label3.UseMarkup = true;
            this.label3.Wrap = true;
            this.vbox3.Add(this.label3);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox3[this.label3]));
            w6.Position = 3;
            w6.Expand = false;
            w6.Fill = false;
            this.notebook1.Add(this.vbox3);
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("About GVisHuff");
            this.notebook1.SetTabLabel(this.vbox3, this.label4);
            this.label4.ShowAll();
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            // Container child vbox4.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("<b>Copyrights</b>");
            this.label2.UseMarkup = true;
            this.vbox4.Add(this.label2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox4[this.label2]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("(c) 2009-2010 Alexander Tarasikov\n(c) 2009-2010 Higher School of Economics, Software Engineering dept.");
            this.label7.Wrap = true;
            this.vbox4.Add(this.label7);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox4[this.label7]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.vbox4.Add(this.hseparator2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox4[this.hseparator2]));
            w10.Position = 2;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("<b>License Information</b>");
            this.label8.UseMarkup = true;
            this.vbox4.Add(this.label8);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox4[this.label8]));
            w11.Position = 3;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("GVisHuff is licensed under the terms of GNU General Public License version 2.0");
            this.label9.Wrap = true;
            this.vbox4.Add(this.label9);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox4[this.label9]));
            w12.Position = 4;
            w12.Expand = false;
            w12.Fill = false;
            this.notebook1.Add(this.vbox4);
            Gtk.Notebook.NotebookChild w13 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
            w13.Position = 1;
            // Notebook tab
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("License Information");
            this.label6.UseMarkup = true;
            this.label6.Wrap = true;
            this.notebook1.SetTabLabel(this.vbox4, this.label6);
            this.label6.ShowAll();
            this.vbox2.Add(this.notebook1);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w15.Position = 0;
            w15.Expand = false;
            w15.Fill = false;
            // Internal child GVisHuff.HSEAboutDialog.ActionArea
            Gtk.HButtonBox w16 = this.ActionArea;
            w16.Name = "dialog1_ActionArea";
            w16.Spacing = 10;
            w16.BorderWidth = ((uint)(5));
            w16.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w17 = ((Gtk.ButtonBox.ButtonBoxChild)(w16[this.buttonOk]));
            w17.Expand = false;
            w17.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 524;
            this.DefaultHeight = 348;
            this.Show();
            this.buttonOk.Clicked += new System.EventHandler(this.OnButtonOkClicked);
        }
    }
}
